INSERT INTO PERSON(login, password) VALUES('misiek', '1qaz');
INSERT INTO PERSON(login, password) VALUES('michal', '1qaz2wsx');
INSERT INTO PERSON(login, password) VALUES('jacek', '123456');
INSERT INTO AUCTION(active, category_id, description, price, title, person_login) VALUES('TRUE',	'4',	'Sprzedam komputer', 	'20.00',	'Apple',	'misiek');
INSERT INTO AUCTION(active, category_id, description, price, title, person_login) VALUES('TRUE',	'6',	'Sprzedam auto', 	'40.00',	'Opel Corsa',	'misiek');
INSERT INTO AUCTION(active, category_id, description, price, title, person_login) VALUES('TRUE',	'5',	'Sprzedam komputer PC', 	'25.00',	'HP',	'misiek');
INSERT INTO AUCTION(active, category_id, description, price, title, person_login) VALUES('TRUE',	'4',	'Sprzedam komputer', 	'30.00',	'HP Elite',	'jacek');
INSERT INTO AUCTION(active, category_id, description, price, title, person_login) VALUES('TRUE',	'6',	'Sprzedam auto', 	'120.00',	'Opel Insignia',	'jacek');
INSERT INTO AUCTION(active, category_id, description, price, title, person_login) VALUES('TRUE',	'7',	'Sprzedam dlugopis', 	'3.00',	'Dlugopis',	'jacek');
INSERT INTO AUCTION(active, category_id, description, price, title, person_login) VALUES('TRUE',	'5',	'Sprzedam tira', 	'5000.00',	'Tir wielki',	'michal');
INSERT INTO AUCTION(active, category_id, description, price, title, person_login) VALUES('TRUE',	'4',	'Sprzedam PC', 	'22.00',	'Apple Big',	'michal');